name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
<<<<<<< HEAD
=======
      - run: pip install mkdocs-aliyun-computenest
>>>>>>> 21a88bb4d8b4e69c9eda628c5130c5eaa8f26454
      - run: mkdocs gh-deploy --force --clean --verbose
